services:
  notificacao:
    container_name: notificacao_blessed
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - notification-maven-cache:/root/.m2
    env_file:
      - .env
    networks:
      - application_network
networks:
  application_network:
    name: application_network
volumes:
  notification-maven-cache: