services:
  rabbitmq:
    image: 'rabbitmq:3.13-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
      - '15672:15672'
  notificacao:
    container_name: notificacao_blessed
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - notification-maven-cache:/root/.m2
    env_file:
      - .env
    networks:
      - application_network
networks:
  application_network:
    name: application_network
volumes:
  notification-maven-cache: